### ISSUE TITLE
go build failed under windows

### ISSUE THREAD

**Issue by AlphaRandom** [estesp/bucketbench#48]
Hi, I cloned your bucketbench project and I'm using GoLand Ide under windows 7. I fixed all dependencies, but when I try compiling I get the following errors :  

GOROOT=C:\Users\Administrator\sdk\go1.13beta1 #gosetup
GOPATH=C:\go;C:\TDM-GCC-64 #gosetup
C:\Users\Administrator\sdk\go1.13beta1\bin\go.exe build -o C:\Users\Administrator\AppData\Local\Temp\___go_build_bucketbench_.exe . #gosetup
# github.com/estesp/bucketbench/vendor/github.com/containerd/containerd/archive
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\containerd\archive\tar_windows.go:227:38: cannot use fileInfo (type *"github.com/Microsoft/go-winio".FileBasicInfo) as type *"github.com/Microsoft/hcsshim/vendor/github.com/Microsoft/go-winio".FileBasicInfo in argument to w.Add
# github.com/estesp/bucketbench/vendor/github.com/containerd/cgroups
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\cgroups\memory.go:179:17: undefined: unix.RawSyscall
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\cgroups\memory.go:179:33: undefined: unix.SYS_EVENTFD2
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\cgroups\memory.go:179:55: undefined: unix.EFD_CLOEXEC
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\cgroups\memory.go:184:3: undefined: unix.Close
C:\go\src\github.com\estesp\bucketbench\vendor\github.com\containerd\cgroups\memory.go:310:16: undefined: unix.EBUSY

So how can I fix them?
Thanks

**Comment by estesp** [comment]
the first one (containerd/archive) probably requires a vendor update to containerd and maybe the MS vendoring--I've never worked with bucketbench on Windows so these compiles haven't really been attempted.

The second one--it could be that some code in bucketbench that uses cgroups needs to partition that code off into a separate file with a build declaration of `!windows`; I don't have a Windows system to test, but I'm happy to accept PRs and if necessary we could set up an AppVeyor CI build to validate it stays working.

**Comment by estesp** [comment]
This should be working now; I'm unable to test it properly on Windows, but the build finishes and builds a proper Windows binary now.
