### ISSUE TITLE
[Containerd] Driver validation: error running test container: rootfs absolute path is required

### ISSUE THREAD

**Issue by visagey** [estesp/bucketbench#54]
Hello,

I am not able to run `examples/ctrd.yaml`, I think there is an issue with Containerd driver.
```shell
$ sudo ./bucketbench --log-level=debug run -b examples/ctrd.yaml --skip-limit 
INFO[0000] driver initialized: containerd (version: '1.2.13', revision: '7ad184331fa3e55e52b890ea95e65ba581ae3429') 
INFO[0000] Attempting to cleanup containerd containers/metadata; 0 listed 
INFO[0000] containerd cleanup complete.                 
Error: error during bench validate: Driver validation: error running test container: rootfs absolute path is required
Usage:
  bucketbench run [flags]

Flags:
  -b, --benchmark string   YAML file with benchmark definition
  -h, --help               help for run
  -o, --overhead           Output daemon overhead
  -s, --skip-limit         Skip 'limit' benchmark run
  -t, --trace              Enable per-container tracing during benchmark runs

Global Flags:
      --log-level string   set the logging level (info,warn,err,debug) (default "warn")

ERRO[0000] Command failed with error: error during bench validate: Driver validation: error running test container: rootfs absolute path is required
```

I am using [Vagrantfile from Kubespray](https://github.com/kubernetes-sigs/kubespray/blob/master/Vagrantfile) (with `containerd` as `container_manager`).

Some information:
```shell
$ ./bucketbench version
bucketbench v0.4.0 (commit: c0e0cc2929852315ae253a0e0c05bf1a35d21027)
```

```shell
$ containerd --version
containerd containerd.io 1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429
```

```shell
$ sudo tree -L 1 /run/containerd
/run/containerd
├── containerd.sock
├── io.containerd.grpc.v1.cri
├── io.containerd.runtime.v1.linux
├── io.containerd.runtime.v2.task
└── runc
```

```shell
$ systemctl is-active containerd.service 
active
```

Let me know if you need more information.

**Comment by visagey** [comment]
@estesp I figured out the issue:
```go
func isRootfsAbs(root string) bool {
	return filepath.IsAbs(root)
}
```
`root` string is `rootfs`.
It looks like `s.Root.Path` variable is never assigned, since `WithRootFSPath() function` is not called.

If I put `return true` in `isRootfsAbs`, it "works", but it is not a proper fix.

**Comment by estesp** [comment]
Looking at this; must be the way I'm forming the container helpers

**Comment by estesp** [comment]
Ordering was wrong. Fixed in https://github.com/estesp/bucketbench/commit/4c8d0c2a6d66bf85e70b851a8d48cdc8598dbd1c

I'm not sure how old it will support re: containerd version. It should definitely support v1.3.x and v1.4.x (in beta now).

**Comment by visagey** [comment]
Nice. By default, bucketbench tries to use `containerd-shim-runc-v2` binary, but according to containerd/containerd#3894, runc-v2 is the default since containerd 1.4.
For previous containerd versions, `containerd-shim-runc-v1` binary seems present since containerd-1.2.13-3.2.el7 on RHEL/CentOS 7.

BTW, thank you for this useful benchmark!

**Comment by estesp** [comment]
Yeah, so updating the vendoring means I get the `DefaultRuntime` from the `defaults` package, which is the v2 shim in the vendor level I'm using now. I guess I should add a config option to specify an older shim in case people are using this with older versions of containerd.
